### ISSUE TITLE
Plugin issue using Jet Brains WebStorm IDE

### ISSUE THREAD

**Issue by LinuxUser255** [sandipchitale/springinitializr#1]
**screen shot**
![springinitializar-error](https://github.com/sandipchitale/springinitializr/assets/46334926/278d1196-3055-45ba-8d95-95b47f7c0a0d)
 
**Full Text Here**
[spring-initializer-issue-06-16-2023.txt](https://github.com/sandipchitale/springinitializr/files/11774331/spring-initializer-issue-06-16-2023.txt)

**Comment by Ali-Panjwani** [comment]
The issue is occurring due to `SwingUtilities.invokeLater()` in file SpringInitializr\src\main\java\sandipchitale\SpringInitializrToolWindow.java.

Instead use `ApplicationManager.getApplication().invokeLater()`. This API allows specifying the modality state for the call.

For further information, read this: https://consulo.dev/basics/architectural_overview/general_threading_rules/

**Comment by sandipchitale** [comment]
@Ali-Panjwani Thanks. Fixed.
